[package]
name = "custom_interface"
version = "0.0.0"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde']
